# Generated by Django 5.0.3 on 2025-01-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_remove_event_category_event_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='categories',
        ),
    ]
