# Generated by Django 5.1.5 on 2025-01-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_category_event_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('social', 'Social Development'), ('senior', 'Senior Citizen')], default='education', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
