# Generated by Django 5.1.5 on 2025-02-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_category_volunteerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Waiting List', 'Waiting List')], default='registered', max_length=20),
        ),
    ]
