# Generated by Django 5.1.5 on 2025-02-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comments',
            new_name='additional_feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_1',
            field=models.CharField(choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], default='Neutral', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_2',
            field=models.CharField(choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], default='Neutral', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_3',
            field=models.CharField(choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], default='Neutral', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_4',
            field=models.CharField(choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], default='Neutral', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_5',
            field=models.CharField(choices=[('Strongly Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly Agree', 'Strongly Agree')], default='Neutral', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
