# Generated by Django 5.1.5 on 2025-02-17 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_comments_feedback_additional_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('question_1', models.CharField(default='How would you rate the overall event experience?', max_length=255)),
                ('question_2', models.CharField(default='How would you rate the registration process?', max_length=255)),
                ('question_3', models.CharField(default='How would you rate the event location/venue?', max_length=255)),
                ('question_4', models.CharField(default='How would you rate the event schedule and timing?', max_length=255)),
                ('question_5', models.CharField(default='How would you rate the communication before, during, and after the event?', max_length=255)),
                ('additional_question_1', models.TextField(blank=True, null=True)),
                ('additional_question_2', models.TextField(blank=True, null=True)),
                ('notify_future_events', models.BooleanField(default=True)),
                ('allow_follow_up_contact', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_form', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_1', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rating_2', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rating_3', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rating_4', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rating_5', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('additional_answer_1', models.TextField(blank=True, null=True)),
                ('additional_answer_2', models.TextField(blank=True, null=True)),
                ('notify_future_events', models.BooleanField(default=False)),
                ('allow_follow_up_contact', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.feedbackform')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
