# Generated by Django 5.1.5 on 2025-02-17 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_feedbackform_feedbackresponse_delete_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='additional_question_1',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Question 1'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='additional_question_2',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Question 2'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='allow_follow_up_contact',
            field=models.BooleanField(default=True, verbose_name='Can we contact you for follow-up?'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_feedback_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='notify_future_events',
            field=models.BooleanField(default=True, verbose_name='Would you like to be notified about future events?'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='additional_answer_1',
            field=models.TextField(blank=True, null=True, verbose_name='Response to Additional Question 1'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='additional_answer_2',
            field=models.TextField(blank=True, null=True, verbose_name='Response to Additional Question 2'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='allow_follow_up_contact',
            field=models.BooleanField(default=False, verbose_name='Can we contact you for follow-up?'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='notify_future_events',
            field=models.BooleanField(default=False, verbose_name='Would you like to be notified about future events?'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
