# Generated by Django 5.1.5 on 2025-03-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_feedbackform_additional_question_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('social development', 'Social Development'), ('senior citizen', 'Senior Citizen')], default='Education', max_length=50),
        ),
    ]
