# Generated by Django 5.1.5 on 2025-03-04 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_duration_hours_volunteerparticipation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
